spring.application.name=holamundo
# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/northwind_springboot
spring.datasource.username=postgres
spring.datasource.password=40888919

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect